const QUESTIONS = [
  // F/L
  { text: "嫌いな相手の意見でも、正しいと思えば認められる", axis: "F", reverse: false, tag: "思考" },
  { text: "好きな相手でも、おかしいと思ったら疑える", axis: "F", reverse: false, tag: "思考" },
  { text: "物事は白黒はっきりさせたい方だ", axis: "F", reverse: true, tag: "思考" },
  { text: "不快でも筋が通っている意見なら聞く価値がある", axis: "F", reverse: false, tag: "思考" },
  { text: "議論では『どちらにも一理ある』と思うことが多い", axis: "F", reverse: false, tag: "思考" },
  { text: "自分の考えが変わることはあまりない方だ", axis: "F", reverse: true, tag: "思考" },
  { text: "感情とは別に、意見の中身だけで判断したい", axis: "F", reverse: false, tag: "思考" },
  { text: "人や物事をすぐ善悪で分けてしまう", axis: "F", reverse: true, tag: "思考" },
  { text: "相手の立場を想像してから判断することが多い", axis: "F", reverse: false, tag: "思考" },
  { text: "自分と違う価値観は理解しにくい", axis: "F", reverse: true, tag: "思考" },
  { text: "結論を急がず保留したまま考えられる", axis: "F", reverse: false, tag: "思考" },
  { text: "対立している両者の主張を並べて見たい", axis: "F", reverse: false, tag: "思考" },

  // C/X
  { text: "親しい相手からの強めの言葉なら冗談として受け取りやすい", axis: "C", reverse: false, tag: "関係性" },
  { text: "知らない人からの強めの言葉でもあまり気にしない", axis: "C", reverse: true, tag: "関係性" },
  { text: "相手との距離感で同じ言葉でも意味が変わると思う", axis: "C", reverse: false, tag: "関係性" },
  { text: "親しくない相手からいじられてもわりと流せる方だ", axis: "C", reverse: true, tag: "関係性" },
  { text: "言い方より『誰が言ったか』の方が大きい", axis: "C", reverse: false, tag: "関係性" },
  { text: "関係性に関係なく中身が同じなら反応もだいたい同じだ", axis: "C", reverse: true, tag: "関係性" },
  { text: "親しい相手には多少強いノリでも許容しやすい", axis: "C", reverse: false, tag: "関係性" },
  { text: "初対面や距離のある相手にも比較的フラットに接しやすい", axis: "C", reverse: true, tag: "関係性" },
  { text: "親しい相手の失礼はある程度なら流せる", axis: "C", reverse: false, tag: "関係性" },
  { text: "知らない人ともすぐに軽口を言い合える方だ", axis: "C", reverse: true, tag: "関係性" },
  { text: "信頼関係がない相手の言葉は重く受けやすい", axis: "C", reverse: false, tag: "関係性" },
  { text: "相手との距離感をあまり意識せず話せる", axis: "C", reverse: true, tag: "関係性" },

  // S/V (Stable/Vibe)
  { text: "言われたことを後から長く引きずることは少ない", axis: "S", reverse: false, tag: "感情安定" },
  { text: "その場で平気でも後でダメージが来ることが多い", axis: "S", reverse: true, tag: "感情安定" },
  { text: "批判されても比較的すぐ立て直せる", axis: "S", reverse: false, tag: "感情安定" },
  { text: "相手の一言で気分がかなり左右されやすい", axis: "S", reverse: true, tag: "感情安定" },
  { text: "議論や対立のあとも気持ちの切り替えは早い方だ", axis: "S", reverse: false, tag: "感情安定" },
  { text: "冗談でも深読みしてしまって疲れることがある", axis: "S", reverse: true, tag: "感情安定" },
  { text: "少しきつい言葉を受けても自分の芯はぶれにくい", axis: "S", reverse: false, tag: "感情安定" },
  { text: "対人関係の温度差にかなり消耗しやすい", axis: "S", reverse: true, tag: "感情安定" },
  { text: "嫌なことがあっても寝るとリセットしやすい", axis: "S", reverse: false, tag: "感情安定" },
  { text: "人の機嫌が悪いと必要以上に気にしてしまう", axis: "S", reverse: true, tag: "感情安定" },
  { text: "衝突のあとでも普段通りに戻りやすい", axis: "S", reverse: false, tag: "感情安定" },
  { text: "些細な言い方の違いがずっと気になる", axis: "S", reverse: true, tag: "感情安定" },

  // K/R (Keep/Rush)
  { text: "感情的になっても表にはあまり出さない", axis: "K", reverse: false, tag: "反応" },
  { text: "思ったことが顔や態度に出やすい", axis: "K", reverse: true, tag: "反応" },
  { text: "勢いで発言するより一度飲み込むことが多い", axis: "K", reverse: false, tag: "反応" },
  { text: "カッとなるとその場で言い返しやすい", axis: "K", reverse: true, tag: "反応" },
  { text: "衝突が起きても一旦落ち着いてから考える", axis: "K", reverse: false, tag: "反応" },
  { text: "思いついたらすぐ口に出しやすい", axis: "K", reverse: true, tag: "反応" },
  { text: "自分の反応をある程度コントロールできる", axis: "K", reverse: false, tag: "反応" },
  { text: "勢いで行動してから考えることが多い", axis: "K", reverse: true, tag: "反応" },
  { text: "場が荒れても必要以上に巻き込まれない", axis: "K", reverse: false, tag: "反応" },
  { text: "テンションが上がると抑えが効かなくなる", axis: "K", reverse: true, tag: "反応" },
  { text: "強い感情でも一度整理してから言葉にする", axis: "K", reverse: false, tag: "反応" },
  { text: "勢いで話を進めるのが得意だ", axis: "K", reverse: true, tag: "反応" },

  // M 12
  { text: "好きな人ならちょっと意地悪されても嬉しい", axis: "M", reverse: false, tag: "M傾向" },
  { text: "正直、いじられる側のポジションが多い", axis: "M", reverse: false, tag: "M傾向" },
  { text: "軽く罵倒されるとちょっとドキッとする", axis: "M", reverse: false, tag: "M傾向" },
  { text: "好きな人に振り回されるの、ちょっと好き", axis: "M", reverse: false, tag: "M傾向" },
  { text: "強めの性格の人に弱い", axis: "M", reverse: false, tag: "M傾向" },
  { text: "からかわれるとむしろテンション上がる", axis: "M", reverse: false, tag: "M傾向" },
  { text: "いじられるキャラだと思う", axis: "M", reverse: false, tag: "M傾向" },
  { text: "『踏まれてみたい』ネタ、実はちょっと分かる", axis: "M", reverse: false, tag: "M傾向" },
  { text: "守るより守られたい", axis: "M", reverse: false, tag: "M傾向" },
  { text: "主導権を渡す方が楽", axis: "M", reverse: false, tag: "M傾向" },
  { text: "相手に支配される関係、少し憧れる", axis: "M", reverse: false, tag: "M傾向" },
  { text: "怒られるとちょっと嬉しい自分がいる", axis: "M", reverse: false, tag: "M傾向" },

  // S 12
  { text: "人をからかうのが好き", axis: "SM_S", reverse: false, tag: "S傾向" },
  { text: "好きな人をいじめたくなる", axis: "SM_S", reverse: false, tag: "S傾向" },
  { text: "恋愛では主導権を握りたい", axis: "SM_S", reverse: false, tag: "S傾向" },
  { text: "相手を翻弄するのが楽しい", axis: "SM_S", reverse: false, tag: "S傾向" },
  { text: "反応を見るのが好き", axis: "SM_S", reverse: false, tag: "S傾向" },
  { text: "軽く命令するのが好き", axis: "SM_S", reverse: false, tag: "S傾向" },
  { text: "つい相手をいじってしまう", axis: "SM_S", reverse: false, tag: "S傾向" },
  { text: "挑発するのが好き", axis: "SM_S", reverse: false, tag: "S傾向" },
  { text: "相手を困らせるのが楽しい", axis: "SM_S", reverse: false, tag: "S傾向" },
  { text: "『ドSだね』って言われたことがある", axis: "SM_S", reverse: false, tag: "S傾向" },
  { text: "相手を振り回すタイプだと思う", axis: "SM_S", reverse: false, tag: "S傾向" },
  { text: "攻める側が好き", axis: "SM_S", reverse: false, tag: "S傾向" }
];
